#! /usr/bin/env python

import sys
import argparse
import os


def main():

	prog = "depth_tool"
	parser = argparse.ArgumentParser(prog = prog)
	#parser.add_argument("--version", action = "version", version = prog + "-" + __version__)
	#subparsers = parser.add_subparsers()


	arg_parser = parser.add_argument("bam_file", help="input bam file path (bam format required)")
	arg_parser = parser.add_argument("bed_file", help="input reference beit file path (bed format required)")
	arg_parser = parser.add_argument("out_file", help="output file path")


	argv = sys.argv[1:]
	if len(argv) < 1:
		argv = [""]
	args = parser.parse_args(argv)

	bamfile = args.bam_file
	bedfile = args.bed_file
	outfile = args.out_file

	if not os.path.exists(bamfile):
		print "Error: bamfile not exists."
		sys.exit()

	if not os.path.exists(bedfile):
		print "Error: beitfile not exists."
		sys.exit()


	import depth_tool.run as run

	run(bamfile, bedfile, outfile)



if __name__ == "__main__":
	main()




